Feature/6-7 api tests
ALEXANCHESSS/TaskManager pull request #15
Opened 2024-06-29 23:41 UTC by ALEXANCHESSS

2024-07-01 06:09 UTC, aleksandr-semenov-dbp requested changes

2024-07-01 06:09 UTC, aleksandr-semenov-dbp commented on test/filters/test_task_filters.py
> +        response = self.list({"title": task1.title})
В dualboot мы обязательно делим тест пустыми строками на 3 части - сетап, тестируемый метод, проверки. Перед этой строкой тоже нужна пустая строка (и далее)

2024-07-01 06:09 UTC, aleksandr-semenov-dbp commented on test/filters/test_task_filters.py
> +        self.assertIn(task1.title, title)
больше затачиваемся на pytest, предпочитаем `assert task1.title in titles`

2024-07-01 06:09 UTC, aleksandr-semenov-dbp commented on test/test_admin.py
> +    def get_assert_forms(
этот тест проверяет наличие форм в админке

2024-07-01 06:09 UTC, aleksandr-semenov-dbp commented on test/test_admin.py
> +    def delete_assert_forms(cls, model: Type[models.Model], key: int) -> None:
Это немножко из другой оперы, возможность удаления объектов лучше тестировать для каждого объекта в его тестах, она с админкой не связана

2024-07-01 06:09 UTC, aleksandr-semenov-dbp commented on test/viewSets/test_status_view_set.py
> +        self.create(status_data)
Даже в совсем тривиальных тестах отделяем пустыми строками сетап, тестируемое и проверку. 
Надо проверить возврат что создалось именно с тем статусом что мы пытались. И далее, сделать простые проверки на объект(ы) который вернется

2024-07-01 17:26 UTC, ALEXANCHESSS commented on test/viewSets/test_status_view_set.py
> +        self.create(status_data)
в base.py в методах create и update уже присутствует метод assert_details для проверки отправленных и полученных данных

2024-07-08 05:48 UTC, aleksandr-semenov-dbp requested changes

2024-07-08 05:48 UTC, aleksandr-semenov-dbp commented on test/viewSets/test_status_view_set.py
> +        self.create(status_data)
Да, незаметил. Неплохая автоматизация, но не очень гибко, правильно работает только в довольно тривиальных ситуациях. Надо предусмотрть какое-то управление таким поведением. Например если мы захотим ограничить набор валидных статусов или сделаем сериализатор, который выдает больше информации об авторе и исполнителе задачи. 
Давай добавим в сериализатор задачи имена автора и исполнителя (на практике так обычно и делается) и доработаем здесь такую возможность.

2024-07-15 04:51 UTC, aleksandr-semenov-dbp approved these changes

2024-07-15 04:51 UTC, aleksandr-semenov-dbp commented on test/base.py
> +                ]["id"]
вот поэтому мы используем форматтеры, IDE-шки ужасно форматируют :)

2024-07-15 04:51 UTC, aleksandr-semenov-dbp commented on main/serializers.py
> +    def to_representation(self, instance):
Хорошее решение, годится, у нас есть специальные классы для этого, ты наверное уже видел. 
Но вообще очень не любим перегрузку to_representation/to_internal_value и MethodFieldы так как убивается вся идея декларативного сериализатора.
Здесь можно было попробовать решить через ReadOnly поля и очистку принимаемых данных в validate()

2024-07-15 21:03 UTC, merged